import Link from "next/link";
import { Suspense } from "react";
import { prisma } from "@/lib/db";
import { formatDate } from "@/lib/utils";
import { PageHeader } from "@/components/page-header";
import { PrintButton } from "@/components/admin-controls";
import { RegisterBookPicker } from "@/components/pickers";
import { EmptyState } from "@/components/ui-system";
import { documentTypeLabels, labelFor } from "@/lib/labels";

export const metadata = { title: "Ewidencja broni" };

export default async function Page({ searchParams }: { searchParams: Promise<{ book?: string }> }) {
  const requested = (await searchParams).book; const books = await prisma.registerBook.findMany({ where: { type: "WEAPON" }, orderBy: { series: "asc" } });
  if (!books.length) return <div className="page"><PageHeader eyebrow="Rejestry zgodne z prawem" title="Ewidencja posiadanej broni" description="Układ pól odpowiada papierowej ewidencji." /><section className="page-card"><EmptyState title="Brak księgi broni" description="Administrator musi najpierw utworzyć księgę ewidencji broni." /></section></div>;
  const selected = books.find((book) => book.id === requested) ?? books[0];
  const weapons = await prisma.weapon.findMany({ where: { bookId: selected.id }, include: { caliber: true, acquisitionDocument: true, events: { where: { type: { in: ["TRANSFERRED", "WITHDRAWN", "DEREGISTERED"] } }, include: { document: true }, orderBy: { effectiveAt: "desc" } } }, orderBy: { positionNo: "asc" } });
  return <div className="page"><PageHeader eyebrow="Rejestry zgodne z prawem" title="Ewidencja posiadanej broni" description="W danym momencie widoczna jest jedna wybrana księga." actions={<PrintButton />} /><section className="book-selector-card no-print"><Suspense><RegisterBookPicker books={books} selectedId={selected.id} storageKey="pmb:weapon-register-book" /></Suspense></section><section className="page-card"><div className="paper-table-wrap"><table className="legal-register"><caption>Księga {selected.series} — {selected.name}</caption><thead><tr><th>Lp</th><th>Nazwa i marka broni</th><th>Kaliber broni i rok produkcji</th><th>Seria i numer broni</th><th>Inne cechy identyfikacyjne, w tym wyposażenie dodatkowe</th><th>Podstawa nabycia lub przejęcia</th><th>Data zewidencjonowania</th><th>Podstawa i data przekazania</th><th>Podstawa i data zdjęcia z ewidencji</th></tr></thead><tbody>{weapons.map((weapon) => { const transfer = weapon.events.find((event) => event.type === "TRANSFERRED"); const removal = weapon.events.find((event) => event.type === "WITHDRAWN" || event.type === "DEREGISTERED"); return <tr key={weapon.id}><td><Link className="registry-link" href={`/weapons/${weapon.id}`}>{weapon.positionNo}</Link></td><td><Link className="record-link" href={`/weapons/${weapon.id}`}>{weapon.name} / {weapon.brand}<small>{weapon.registryRef}</small></Link></td><td>{weapon.caliber.canonicalName}{weapon.productionYear ? ` / ${weapon.productionYear}` : ""}</td><td>{weapon.weaponSeries ? `${weapon.weaponSeries} / ` : ""}{weapon.serialNumber}</td><td>{[weapon.otherIdentifyingMarks, weapon.accessories].filter(Boolean).join("; ") || "—"}</td><td>{weapon.acquisitionBasis}<Link className="document-link compact-link" href={`/documents/${weapon.acquisitionDocument.id}`}>{labelFor(documentTypeLabels, weapon.acquisitionDocument.type, "Inny dokument")} {weapon.acquisitionDocument.number || weapon.acquisitionDocument.description}</Link></td><td>{formatDate(weapon.registeredAt)}</td><td>{transfer ? <>{transfer.basis || "Przekazanie"}{transfer.document && <Link className="document-link compact-link" href={`/documents/${transfer.document.id}`}>{labelFor(documentTypeLabels, transfer.document.type, "Inny dokument")} {transfer.document.number || transfer.document.description}</Link>}<small>{formatDate(transfer.effectiveAt)}</small></> : "—"}</td><td>{removal ? <>{removal.basis || "Zdjęcie z ewidencji"}{removal.document && <Link className="document-link compact-link" href={`/documents/${removal.document.id}`}>{labelFor(documentTypeLabels, removal.document.type, "Inny dokument")} {removal.document.number || removal.document.description}</Link>}<small>{formatDate(removal.effectiveAt)}</small></> : "—"}</td></tr>; })}{!weapons.length && <tr><td colSpan={9} className="muted">Ta księga nie zawiera jeszcze wpisów.</td></tr>}</tbody></table></div></section></div>;
}
