"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Save } from "lucide-react";
import { InlineAlert } from "@/components/ui-system";
import { dashboardActionKeys, dashboardActionLabels, dashboardActionTones, dashboardToneLabels, type DashboardActionColors } from "@/lib/settings";

export function UserStatusButton({ id, active }: { id: string; active: boolean }) {
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const router = useRouter(); return <div className="table-action">{error && <span className="field-error">{error}</span>}<button className={`button ${active ? "danger" : ""}`} disabled={loading} onClick={async () => { setLoading(true); setError(""); const response = await fetch("/api/users", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, active: !active }) }); const body = await response.json(); if (!response.ok) setError(body.error); else router.refresh(); setLoading(false); }}>{active ? "Dezaktywuj" : "Aktywuj"}</button></div>;
}

export function SettingsForm({ showInactive, groupWeaponsByType, dashboardActionColors, backupHour, backupMinute }: { showInactive: boolean; groupWeaponsByType: boolean; dashboardActionColors: DashboardActionColors; backupHour: number; backupMinute: number }) {
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const [colors, setColors] = useState(dashboardActionColors);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(""); setMessage(""); const data = new FormData(event.currentTarget); const response = await fetch("/api/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ showInactiveWeaponsInGrid: data.get("showInactive") === "on", groupWeaponsByType: data.get("groupWeaponsByType") === "on", dashboardActionColors: colors, backupHour: Number(data.get("backupHour")), backupMinute: Number(data.get("backupMinute")) }) }); const body = await response.json(); if (!response.ok) setError(body.error); else setMessage("Ustawienia zostały zapisane."); setLoading(false); }
  return <form className="form-stack settings-form" onSubmit={submit}>{error && <InlineAlert tone="error">{error}</InlineAlert>}{message && <InlineAlert tone="success">{message}</InlineAlert>}<section className="settings-section"><h2 className="section-heading">Widoki broni</h2><label className="checkbox-field"><input type="checkbox" name="showInactive" defaultChecked={showInactive} /> Pokazuj wycofane i nieaktywne egzemplarze w gridzie wydawania</label><label className="checkbox-field"><input type="checkbox" name="groupWeaponsByType" defaultChecked={groupWeaponsByType} /> Dziel gridy na broń krótką, długą i inne</label></section><section className="settings-section"><h2 className="section-heading">Kolory akcji na pulpicie</h2><p className="muted small">Każdej akcji możesz przypisać niezależny, kontrastowy kolor.</p><div className="action-color-settings">{dashboardActionKeys.map((key) => <div className="action-color-row" key={key}><span className={`action-color-preview action-tone-${colors[key]}`}>{dashboardActionLabels[key]}</span><div className="tone-options" role="radiogroup" aria-label={`Kolor: ${dashboardActionLabels[key]}`}>{dashboardActionTones.map((tone) => <label title={dashboardToneLabels[tone]} key={tone}><input type="radio" name={`color-${key}`} value={tone} checked={colors[key] === tone} onChange={() => setColors((current) => ({ ...current, [key]: tone }))} /><span className={`tone-swatch action-tone-${tone}`}><span className="visually-hidden">{dashboardToneLabels[tone]}</span></span></label>)}</div></div>)}</div></section><section className="settings-section"><h2 className="section-heading">Kopie zapasowe</h2><div className="form-grid"><div className="field"><label htmlFor="backupHour">Godzina automatycznego backupu</label><input className="input" id="backupHour" name="backupHour" type="number" min="0" max="23" defaultValue={backupHour} /></div><div className="field"><label htmlFor="backupMinute">Minuta</label><input className="input" id="backupMinute" name="backupMinute" type="number" min="0" max="59" defaultValue={backupMinute} /></div></div></section><button className="button primary" disabled={loading} style={{ width: "fit-content" }}><Save size={17} />Zapisz ustawienia</button></form>;
}

export function PrintButton() { return <button className="button no-print" onClick={() => window.print()}>Drukuj / zapisz jako PDF</button>; }
