"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState, type FormEvent } from "react";
import { CalendarRange, FilePenLine, Paperclip, Search, Trash2 } from "lucide-react";
import { AttachmentUploader } from "@/components/attachment-uploader";
import { InlineAlert } from "@/components/ui-system";
import { documentTypeLabels } from "@/lib/labels";

type Attachment = { id: string; originalName: string; mimeType: string; sizeBytes: number; createdAt: string };
type DocumentRow = { id: string; type: string; number: string | null; documentDate: string; description: string; parties: string | null; attachments: Attachment[]; referenceCount: number };

const labels: Record<string, string> = documentTypeLabels;

async function json(response: Response) { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Operacja nie powiodła się."); return body; }

export function DocumentRegistry({ documents }: { documents: DocumentRow[] }) {
  const [search, setSearch] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [type, setType] = useState("");
  const filtered = useMemo(() => documents.filter((document) => { const day = document.documentDate.slice(0, 10); const needle = search.toLocaleLowerCase("pl-PL"); return (!needle || [document.number, document.description, document.parties, labels[document.type]].filter(Boolean).join(" ").toLocaleLowerCase("pl-PL").includes(needle)) && (!from || day >= from) && (!to || day <= to) && (!type || document.type === type); }), [documents, from, search, to, type]);
  return <><div className="filter-bar"><label className="filter-search"><Search aria-hidden /><input aria-label="Szukaj dokumentów" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Numer, nazwa, typ lub podmiot…" /></label><label><CalendarRange aria-hidden /><span>Od</span><input aria-label="Data dokumentu od" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label><span>Do</span><input aria-label="Data dokumentu do" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label><select aria-label="Typ dokumentu" value={type} onChange={(event) => setType(event.target.value)}><option value="">Wszystkie typy</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="paper-table-wrap"><table className="paper-table"><thead><tr><th>Data</th><th>Typ i numer</th><th>Opis</th><th>Podmioty</th><th>Pliki</th><th>Użycia</th><th>Akcja</th></tr></thead><tbody>{filtered.map((document) => <tr key={document.id}><td>{new Date(document.documentDate).toLocaleDateString("pl-PL")}</td><td><Link className="document-link" href={`/documents/${document.id}`}><FilePenLine aria-hidden />{labels[document.type]} {document.number || "bez numeru"}</Link></td><td>{document.description}</td><td>{document.parties || "—"}</td><td><span className="attachment-count"><Paperclip aria-hidden />{document.attachments.length}</span></td><td>{document.referenceCount}</td><td><Link className="button compact" href={`/documents/${document.id}`}>Podgląd / edycja</Link></td></tr>)}{!filtered.length && <tr><td colSpan={7} className="muted">Brak dokumentów spełniających kryteria.</td></tr>}</tbody></table></div></>;
}

export function DocumentDetailEditor({ document }: { document: DocumentRow }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function update(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setLoading(true); setError(""); try { await json(await fetch("/api/documents", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: document.id, type: data.get("type"), number: data.get("number") || undefined, documentDate: data.get("documentDate"), description: data.get("description"), parties: data.get("parties") || undefined }) })); const files = data.getAll("files").filter((value): value is File => value instanceof File && value.size > 0); for (const file of files) { const upload = new FormData(); upload.set("documentId", document.id); upload.set("file", file); await json(await fetch("/api/attachments", { method: "POST", body: upload })); } setMessage("Dokument i załączniki zostały zaktualizowane."); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Nie udało się zaktualizować dokumentu."); } finally { setLoading(false); } }
  async function removeAttachment(id: string) { setError(""); try { await json(await fetch(`/api/attachments?id=${id}`, { method: "DELETE" })); setMessage("Załącznik został usunięty."); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Nie udało się usunąć załącznika."); } }
  async function removeDocument() { if (!window.confirm("Usunąć dokument? Operacja jest możliwa tylko wtedy, gdy dokument nie ma referencji biznesowych.")) return; setError(""); try { await json(await fetch(`/api/documents?id=${document.id}`, { method: "DELETE" })); router.push("/documents"); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Nie udało się usunąć dokumentu."); } }
  return <div className="form-stack">{error && <InlineAlert tone="error">{error}</InlineAlert>}{message && <InlineAlert tone="success">{message}</InlineAlert>}<form className="form-stack" onSubmit={update}><div className="form-grid"><div className="field"><label htmlFor="edit-type">Typ dokumentu</label><select className="select" id="edit-type" name="type" defaultValue={document.type}>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="field"><label htmlFor="edit-number">Numer / oznaczenie</label><input className="input" id="edit-number" name="number" defaultValue={document.number ?? ""} /></div><div className="field"><label htmlFor="edit-date">Data dokumentu</label><input className="input" id="edit-date" name="documentDate" type="date" defaultValue={document.documentDate.slice(0, 10)} required /></div><div className="field full"><label htmlFor="edit-description">Opis / nazwa</label><input className="input" id="edit-description" name="description" defaultValue={document.description} required /></div><div className="field full"><label htmlFor="edit-parties">Strony / podmioty</label><input className="input" id="edit-parties" name="parties" defaultValue={document.parties ?? ""} /></div><div className="field full"><AttachmentUploader /></div></div><button className="button primary" disabled={loading}><FilePenLine aria-hidden />{loading ? "Zapisywanie…" : "Zapisz zmiany i dodane pliki"}</button></form><section><h2 className="section-heading">Załączniki ({document.attachments.length})</h2>{document.attachments.length ? <div className="attachment-list">{document.attachments.map((file) => <div key={file.id}><a href={`/api/attachments?id=${file.id}`} target="_blank" rel="noreferrer"><Paperclip aria-hidden /><span><strong>{file.originalName}</strong><small>{file.mimeType} · {(file.sizeBytes / 1024).toLocaleString("pl-PL", { maximumFractionDigits: 1 })} KB</small></span></a><button type="button" className="close-button danger-icon" aria-label={`Usuń ${file.originalName}`} onClick={() => void removeAttachment(file.id)}><Trash2 /></button></div>)}</div> : <p className="muted">Dokument nie ma jeszcze załączników.</p>}</section><div className="danger-zone"><div><strong>Usunięcie dokumentu</strong><p>Dozwolone wyłącznie dla dokumentu bez referencji biznesowych. Aktualna liczba użyć: {document.referenceCount}.</p></div><button type="button" className="button danger" onClick={() => void removeDocument()}><Trash2 aria-hidden />Usuń dokument</button></div></div>;
}
