"use client";

import { useState, type FormEvent } from "react";
import { CheckCircle2, Download, ShieldCheck, Upload } from "lucide-react";

type Option = { id: string; name?: string; canonicalName?: string; series?: string; description?: string; number?: string | null; registryRef?: string; available?: number };
type AmmoIssueOption = { id: string; registryRef: string; recipientName: string; quantityIssued: number; caliberSnapshot: string; ammunitionType: string };

async function requestJson(url: string, body: unknown, method = "POST") {
  const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json();
  if (!response.ok) throw new Error(result.error ?? "Nie udało się wykonać operacji."); return result;
}

function useResult() {
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  return { loading, error, success, run: async (action: () => Promise<string>) => { setLoading(true); setError(""); setSuccess(""); try { setSuccess(await action()); } catch (err) { setError(err instanceof Error ? err.message : "Nieznany błąd."); } finally { setLoading(false); } } };
}

function Messages({ error, success }: { error: string; success: string }) { return <>{error && <div className="error-box" role="alert">{error}</div>}{success && <div className="success-box" role="status"><CheckCircle2 size={17} /> {success}</div>}</>; }
function Submit({ loading, children }: { loading: boolean; children: React.ReactNode }) { return <button className="button primary" disabled={loading}><ShieldCheck size={17} />{loading ? "Zapisywanie…" : children}</button>; }
const nowInput = () => new Date(Date.now() - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 16);

export function AddWeaponForm({ books, calibers, documents }: { books: Option[]; calibers: Option[]; documents: Option[] }) {
  const result = useResult(); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await result.run(async () => { const response = await requestJson("/api/weapons", { bookId: data.get("bookId"), caliberId: data.get("caliberId"), documentId: data.get("documentId"), name: data.get("name"), brand: data.get("brand"), productionYear: data.get("productionYear") || undefined, weaponSeries: data.get("weaponSeries") || undefined, serialNumber: data.get("serialNumber"), otherIdentifyingMarks: data.get("otherIdentifyingMarks") || undefined, accessories: data.get("accessories") || undefined, type: data.get("type"), acquisitionBasis: data.get("acquisitionBasis"), acquisitionDate: data.get("acquisitionDate") || undefined, registeredAt: data.get("registeredAt"), certificateNumber: data.get("certificateNumber") || undefined, notes: data.get("notes") || undefined, pin: data.get("pin") }); form.reset(); return `Broń zewidencjonowano jako ${response.weapon.registryRef}.`; }); }
  return <form className="form-stack" onSubmit={onSubmit}><Messages error={result.error} success={result.success} /><div className="form-grid"><SelectField label="Księga broni" name="bookId" options={books} /><div className="field"><label htmlFor="type">Rodzaj</label><select className="select" id="type" name="type"><option value="HANDGUN">Broń krótka</option><option value="LONG_GUN">Broń długa</option></select></div><TextField label="Nazwa" name="name" required /><TextField label="Marka" name="brand" required /><SelectField label="Kaliber" name="caliberId" options={calibers} canonical /><TextField label="Rok produkcji" name="productionYear" type="number" /><TextField label="Seria broni" name="weaponSeries" /><TextField label="Numer broni" name="serialNumber" required /><TextField label="Numer świadectwa broni" name="certificateNumber" /><TextField label="Wyposażenie dodatkowe" name="accessories" /><TextField label="Podstawa nabycia" name="acquisitionBasis" required full /><SelectField label="Dokument nabycia" name="documentId" options={documents} document full /><TextField label="Data nabycia" name="acquisitionDate" type="datetime-local" /><TextField label="Data zewidencjonowania" name="registeredAt" type="datetime-local" defaultValue={nowInput()} required /><TextArea label="Inne cechy identyfikacyjne" name="otherIdentifyingMarks" /><TextArea label="Uwagi" name="notes" /><PinField /></div><Submit loading={result.loading}>Zewidencjonuj broń</Submit></form>;
}

export function AddAmmoForm({ books, calibers, documents }: { books: Option[]; calibers: Option[]; documents: Option[] }) {
  const result = useResult(); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await result.run(async () => { const response = await requestJson("/api/ammunition/acquire", { bookId: data.get("bookId"), caliberId: data.get("caliberId"), documentId: data.get("documentId"), ammunitionType: data.get("ammunitionType"), quantity: data.get("quantity"), basis: data.get("basis"), effectiveAt: data.get("effectiveAt"), pin: data.get("pin") }); form.reset(); return `Amunicję zewidencjonowano jako ${response.entry.registryRef}. Stan: ${response.entry.balanceAfter} szt.`; }); }
  return <form className="form-stack" onSubmit={onSubmit}><Messages error={result.error} success={result.success} /><div className="form-grid"><SelectField label="Księga amunicji" name="bookId" options={books} /><SelectField label="Kaliber" name="caliberId" options={calibers} canonical /><TextField label="Typ amunicji" name="ammunitionType" defaultValue="pełnopłaszczowa" required /><TextField label="Ilość" name="quantity" type="number" required /><TextField label="Podstawa nabycia / przejęcia" name="basis" required full /><SelectField label="Dokument" name="documentId" options={documents} document full /><TextField label="Data operacji" name="effectiveAt" type="datetime-local" defaultValue={nowInput()} required /><PinField /></div><Submit loading={result.loading}>Dodaj przychód amunicji</Submit></form>;
}

export function IssueAmmoForm({ ammoBooks, issueBooks, calibers, activeIssues }: { ammoBooks: Option[]; issueBooks: Option[]; calibers: Option[]; activeIssues: AmmoIssueOption[] }) {
  const result = useResult(); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await result.run(async () => { const response = await requestJson("/api/operations/issue-ammo", { bookId: data.get("bookId"), sourceBookId: data.get("sourceBookId"), caliberId: data.get("caliberId"), ammunitionType: data.get("ammunitionType"), quantity: data.get("quantity"), recipientName: data.get("recipientName"), recipientReference: data.get("recipientReference") || undefined, parentIssueId: data.get("parentIssueId") || undefined, pin: data.get("pin") }); return `Wydanie amunicji zapisano jako ${response.issue.registryRef}.`; }); }
  return <form className="form-stack" onSubmit={onSubmit}><Messages error={result.error} success={result.success} /><div className="form-grid"><SelectField label="Księga wydawania" name="bookId" options={issueBooks} /><SelectField label="Księga źródłowa" name="sourceBookId" options={ammoBooks} /><SelectField label="Kaliber" name="caliberId" options={calibers} canonical /><TextField label="Typ amunicji" name="ammunitionType" defaultValue="pełnopłaszczowa" required /><TextField label="Ilość" name="quantity" type="number" required /><TextField label="Odbiorca" name="recipientName" required /><TextField label="Dokument / identyfikator odbiorcy" name="recipientReference" /><div className="field"><label htmlFor="parentIssueId">Kontynuacja aktywnego wydania (opcjonalnie)</label><select className="select" id="parentIssueId" name="parentIssueId"><option value="">Nowe niezależne wydanie</option>{activeIssues.map((issue) => <option key={issue.id} value={issue.id}>{issue.registryRef} — {issue.caliberSnapshot}, {issue.recipientName}</option>)}</select></div><PinField /></div><Submit loading={result.loading}>Wydaj amunicję</Submit></form>;
}

export function ReturnAmmoForm({ issues }: { issues: AmmoIssueOption[] }) {
  const result = useResult(); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const issue = issues.find((item) => item.id === data.get("issueId")); await result.run(async () => { const response = await requestJson("/api/operations/return-ammo", { issueId: data.get("issueId"), returnedQuantity: data.get("returnedQuantity"), pin: data.get("pin") }); return `Wydanie zamknięto. Zwrot: ${data.get("returnedQuantity")} szt., rozchód: ${response.consumed} szt.${issue ? ` (${issue.caliberSnapshot})` : ""}`; }); }
  return <form className="form-stack" onSubmit={onSubmit}><Messages error={result.error} success={result.success} /><div className="form-grid"><div className="field full"><label htmlFor="issueId">Aktywne wydanie</label><select className="select" id="issueId" name="issueId" required><option value="">Wybierz wydanie…</option>{issues.map((issue) => <option key={issue.id} value={issue.id}>{issue.registryRef} — {issue.caliberSnapshot}, {issue.quantityIssued} szt., {issue.recipientName}</option>)}</select></div><TextField label="Ilość zwracana" name="returnedQuantity" type="number" defaultValue="0" required /><PinField /></div><Submit loading={result.loading}>Rozlicz i zamknij wydanie</Submit></form>;
}

export function WithdrawWeaponForm({ weapons, documents }: { weapons: Option[]; documents: Option[] }) {
  const result = useResult(); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await result.run(async () => { await requestJson("/api/operations/withdraw-weapon", { weaponId: data.get("weaponId"), documentId: data.get("documentId"), status: data.get("status"), basis: data.get("basis"), recipient: data.get("recipient") || undefined, pin: data.get("pin") }); return "Operacja została zapisana bez usuwania historii broni."; }); }
  return <form className="form-stack" onSubmit={onSubmit}><Messages error={result.error} success={result.success} /><div className="form-grid"><SelectField label="Egzemplarz" name="weaponId" options={weapons} registry full /><div className="field"><label htmlFor="status">Rodzaj operacji</label><select className="select" id="status" name="status"><option value="WITHDRAWN">Wycofanie</option><option value="TRANSFERRED">Przekazanie</option><option value="DEREGISTERED">Zdjęcie z ewidencji</option></select></div><SelectField label="Dokument" name="documentId" options={documents} document /><TextField label="Podstawa i data" name="basis" required full /><TextField label="Jednostka / odbiorca" name="recipient" full /><PinField /></div><Submit loading={result.loading}>Zapisz zdarzenie</Submit></form>;
}

export function DocumentForm() {
  const result = useResult(); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await result.run(async () => { const response = await requestJson("/api/documents", { type: data.get("type"), number: data.get("number") || undefined, documentDate: data.get("documentDate"), description: data.get("description"), parties: data.get("parties") || undefined }); const file = data.get("file"); if (file instanceof File && file.size) { const upload = new FormData(); upload.set("documentId", response.document.id); upload.set("file", file); const uploadResponse = await fetch("/api/attachments", { method: "POST", body: upload }); const uploadResult = await uploadResponse.json(); if (!uploadResponse.ok) throw new Error(`Dokument zapisano, ale załącznik nie został dodany: ${uploadResult.error}`); } form.reset(); return "Dokument zapisano w centralnym rejestrze."; }); }
  return <form className="form-stack" onSubmit={onSubmit}><Messages error={result.error} success={result.success} /><div className="form-grid"><div className="field"><label htmlFor="type">Typ dokumentu</label><select className="select" id="type" name="type"><option value="INVOICE">Faktura</option><option value="AGREEMENT">Umowa</option><option value="TRANSFER_DOCUMENT">Dokument przekazania</option><option value="WITHDRAWAL_DOCUMENT">Dokument wycofania</option><option value="AUTHORIZATION">Upoważnienie</option><option value="OTHER">Inny</option></select></div><TextField label="Numer / oznaczenie" name="number" /><TextField label="Data dokumentu" name="documentDate" type="date" required /><TextField label="Opis" name="description" required full /><TextField label="Strony / podmioty" name="parties" full /><div className="field full"><label htmlFor="file">Załącznik (opcjonalny, PDF/JPG/PNG/WebP do 8 MB)</label><input className="input" id="file" name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" /></div></div><Submit loading={result.loading}><Upload size={17} />Dodaj dokument</Submit></form>;
}

export function BookForm() {
  const result = useResult(); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await result.run(async () => { await requestJson("/api/books", { type: data.get("type"), series: data.get("series"), name: data.get("name") }); form.reset(); return "Księga została utworzona."; }); }
  return <form className="form-stack" onSubmit={onSubmit}><Messages error={result.error} success={result.success} /><div className="form-grid"><div className="field"><label htmlFor="type">Typ księgi</label><select className="select" id="type" name="type"><option value="WEAPON">Ewidencja broni</option><option value="AMMUNITION">Ewidencja amunicji</option><option value="WEAPON_ISSUE">Wydawanie broni</option><option value="AMMUNITION_ISSUE">Wydawanie amunicji</option></select></div><TextField label="Seria (A–ZZ)" name="series" required /><TextField label="Nazwa" name="name" required full /></div><Submit loading={result.loading}>Utwórz księgę</Submit></form>;
}

export function CaliberForm() {
  const result = useResult(); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await result.run(async () => { await requestJson("/api/calibers", { canonicalName: data.get("canonicalName"), aliases: String(data.get("aliases") ?? "").split(",").map((value) => value.trim()).filter(Boolean) }); form.reset(); return "Kaliber i aliasy zostały dodane."; }); }
  return <form className="form-stack" onSubmit={onSubmit}><Messages error={result.error} success={result.success} /><TextField label="Nazwa kanoniczna" name="canonicalName" required /><TextField label="Aliasy rozdzielone przecinkami" name="aliases" /><Submit loading={result.loading}>Dodaj kaliber</Submit></form>;
}

export function UserForm() {
  const result = useResult(); async function onSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await result.run(async () => { await requestJson("/api/users", { firstName: data.get("firstName"), lastName: data.get("lastName"), login: data.get("login"), temporaryPassword: data.get("temporaryPassword"), pin: data.get("pin"), role: data.get("role"), isAuthorized: data.get("isAuthorized") === "on" }); form.reset(); return "Użytkownik został utworzony. Przy pierwszym logowaniu ustawi własne hasło."; }); }
  return <form className="form-stack" onSubmit={onSubmit}><Messages error={result.error} success={result.success} /><div className="form-grid"><TextField label="Imię" name="firstName" required /><TextField label="Nazwisko" name="lastName" required /><TextField label="Login" name="login" required /><TextField label="Hasło jednorazowe" name="temporaryPassword" type="password" required /><PinField /><div className="field"><label htmlFor="role">Rola</label><select className="select" id="role" name="role"><option value="AUTHORIZED">Uprawniony</option><option value="ADMIN">Administrator</option></select></div><label className="field full" style={{ display: "flex", gridTemplateColumns: "auto 1fr", alignItems: "center" }}><input type="checkbox" name="isAuthorized" defaultChecked /> Osoba pisemnie upoważniona do wpisów</label></div><Submit loading={result.loading}>Dodaj użytkownika</Submit></form>;
}

export function BackupControls() {
  const result = useResult(); const [downloadUrl, setDownloadUrl] = useState(""); async function create() { await result.run(async () => { const response = await requestJson("/api/backups", {}); setDownloadUrl(response.downloadUrl); return `Kopia ${response.filename} przeszła walidację.`; }); }
  async function restore(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const file = data.get("backup"); if (!(file instanceof File) || !file.size) return; await result.run(async () => { if (data.get("confirmation") !== "ODTWÓRZ") throw new Error("Aby potwierdzić przywrócenie, wpisz dokładnie ODTWÓRZ."); const response = await fetch("/api/backups", { method: "PUT", headers: { "x-confirm-restore": "ODTWÓRZ" }, body: file }); const body = await response.json(); if (!response.ok) throw new Error(body.error); return "Dane zostały odtworzone i sprawdzone. Odśwież aplikację."; }); }
  return <div className="form-stack"><Messages error={result.error} success={result.success} /><div><button className="button primary" onClick={create} disabled={result.loading}>Utwórz kopię teraz</button>{downloadUrl && <a className="button" href={downloadUrl} style={{ marginLeft: 10 }}><Download size={17} />Pobierz kopię</a>}</div><form className="form-stack" onSubmit={restore}><h3>Odtwórz z kopii</h3><div className="info-box">Przed odtworzeniem system automatycznie zapisze kopię aktualnego stanu i zweryfikuje sumy kontrolne oraz bazę SQLite.</div><input className="input" type="file" name="backup" accept="application/zip,.zip" required /><div className="field"><label htmlFor="restore-confirmation">Wpisz ODTWÓRZ, aby potwierdzić</label><input className="input" id="restore-confirmation" name="confirmation" autoComplete="off" pattern="ODTWÓRZ" required /></div><button className="button danger" disabled={result.loading}>Odtwórz dane z pliku</button></form></div>;
}

export function AuditVerifier() {
  const result = useResult(); return <div className="form-stack"><Messages error={result.error} success={result.success} /><button className="button primary" style={{ width: "fit-content" }} onClick={() => result.run(async () => { const response = await fetch("/api/audit/verify", { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); if (!body.valid) throw new Error(`Wykryto niespójność przy wpisie ${body.brokenAt}.`); return `Zweryfikowano ${body.checked} wpisów. Łańcuch integralności jest prawidłowy.`; })}>Sprawdź integralność</button></div>;
}

function TextField({ label, name, type = "text", required, full, defaultValue }: { label: string; name: string; type?: string; required?: boolean; full?: boolean; defaultValue?: string }) { return <div className={`field ${full ? "full" : ""}`}><label htmlFor={name}>{label}</label><input className="input" id={name} name={name} type={type} required={required} defaultValue={defaultValue} min={type === "number" ? 0 : undefined} /></div>; }
function TextArea({ label, name }: { label: string; name: string }) { return <div className="field"><label htmlFor={name}>{label}</label><textarea className="textarea" id={name} name={name} /></div>; }
function SelectField({ label, name, options, canonical, document, registry, full }: { label: string; name: string; options: Option[]; canonical?: boolean; document?: boolean; registry?: boolean; full?: boolean }) { return <div className={`field ${full ? "full" : ""}`}><label htmlFor={name}>{label}</label><select className="select" id={name} name={name} required><option value="">Wybierz…</option>{options.map((item) => <option value={item.id} key={item.id}>{canonical ? item.canonicalName : document ? `${item.number ? `${item.number} — ` : ""}${item.description}` : registry ? `${item.registryRef} — ${item.name}` : `${item.series ? `${item.series} — ` : ""}${item.name}`}</option>)}</select></div>; }
function PinField() { return <div className="field"><label htmlFor="pin">PIN potwierdzający</label><input className="input pin-input" id="pin" name="pin" type="password" inputMode="numeric" pattern="[0-9]{4}" maxLength={4} required /></div>; }
