"use client";

import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { PinConfirmDialog } from "@/components/pin-confirm-dialog";
import { InlineAlert } from "@/components/ui-system";
import { labelFor, weaponRegisterEventTypeLabels } from "@/lib/labels";

async function send(url: string, body: unknown, method = "POST") { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); return result; }

export function WeaponHistoryControls({ weaponId, entries, openFlags }: { weaponId: string; entries: { id: string; registryRef: string; eventType: string }[]; openFlags: { id: string; reason: string }[] }) {
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [correction, setCorrection] = useState<Record<string, unknown> | null>(null); const router = useRouter();
  async function flag(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await send("/api/verification-flags", { weaponId, reason: data.get("reason") }); setMessage("Pozycję dodano do raportu kontroli."); form.reset(); router.refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Błąd."); } }
  function prepareCorrection(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setError(""); setCorrection({ entityType: "WeaponRegisterEntry", entryId: data.get("entryId"), correctedValues: { [String(data.get("field"))]: data.get("value") }, reason: data.get("reason") }); }
  return <div className="form-stack">{error && <InlineAlert tone="error">{error}</InlineAlert>}{message && <InlineAlert tone="success">{message}</InlineAlert>}<form className="form-stack" onSubmit={flag}><h3>Kontrola fizyczna</h3><div className="field"><label htmlFor="reason">Powód oznaczenia</label><input className="input" id="reason" name="reason" required minLength={5} /></div><button className="button" style={{ width: "fit-content" }}>Oznacz do sprawdzenia</button></form>{openFlags.map((flag) => <InlineAlert tone="warning" key={flag.id}>{flag.reason} <button className="button" onClick={async () => { await send("/api/verification-flags", { id: flag.id }, "PATCH"); router.refresh(); }}>Oznacz jako sprawdzone</button></InlineAlert>)}<form className="form-stack" onSubmit={prepareCorrection}><h3>Skoryguj wpis bez nadpisywania historii</h3><div className="form-grid"><div className="field"><label htmlFor="entryId">Wpis pierwotny</label><select className="select" id="entryId" name="entryId" required>{entries.map((entry) => <option value={entry.id} key={entry.id}>{entry.registryRef} — {labelFor(weaponRegisterEventTypeLabels, entry.eventType, "Inne zdarzenie")}</option>)}</select></div><div className="field"><label htmlFor="field">Korygowane pole</label><input className="input" id="field" name="field" required /></div><div className="field"><label htmlFor="value">Poprawna wartość</label><input className="input" id="value" name="value" required /></div><div className="field full"><label htmlFor="correctionReason">Powód korekty</label><textarea className="textarea" id="correctionReason" name="reason" required minLength={5} /></div></div><button className="button primary" style={{ width: "fit-content" }}>Skoryguj i potwierdź PIN-em</button></form><PinConfirmDialog open={correction !== null} onClose={() => setCorrection(null)} onConfirm={async (pin) => { if (!correction) return; await send("/api/corrections", { ...correction, pin }); setMessage("Korektę zapisano jako nowy wpis; oryginał pozostał bez zmian."); setCorrection(null); router.refresh(); }} /></div>;
}
