"use client";

import { useState, type FormEvent } from "react";

async function send(url: string, body: unknown, method = "POST") { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); return result; }

export function WeaponHistoryControls({ weaponId, entries, openFlags }: { weaponId: string; entries: { id: string; registryRef: string; eventType: string }[]; openFlags: { id: string; reason: string }[] }) {
  const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function flag(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await send("/api/verification-flags", { weaponId, reason: data.get("reason") }); setMessage("Pozycję dodano do raportu kontroli."); form.reset(); window.location.reload(); } catch (err) { setError(err instanceof Error ? err.message : "Błąd."); } }
  async function correction(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); try { await send("/api/corrections", { entityType: "WeaponRegisterEntry", entryId: data.get("entryId"), correctedValues: { [String(data.get("field"))]: data.get("value") }, reason: data.get("reason"), pin: data.get("pin") }); setMessage("Korektę zapisano jako nowy wpis; oryginał pozostał bez zmian."); form.reset(); window.location.reload(); } catch (err) { setError(err instanceof Error ? err.message : "Błąd."); } }
  return <div className="form-stack">{error && <div className="error-box">{error}</div>}{message && <div className="success-box">{message}</div>}<form className="form-stack" onSubmit={flag}><h3>Kontrola fizyczna</h3><div className="field"><label htmlFor="reason">Powód oznaczenia</label><input className="input" id="reason" name="reason" required minLength={5} /></div><button className="button" style={{ width: "fit-content" }}>Oznacz do sprawdzenia</button></form>{openFlags.map((flag) => <div className="info-box" key={flag.id}>{flag.reason} <button className="button" style={{ marginLeft: 10 }} onClick={async () => { await send("/api/verification-flags", { id: flag.id }, "PATCH"); window.location.reload(); }}>Oznacz jako sprawdzone</button></div>)}<form className="form-stack" onSubmit={correction}><h3>Skoryguj wpis bez nadpisywania historii</h3><div className="form-grid"><div className="field"><label htmlFor="entryId">Wpis pierwotny</label><select className="select" id="entryId" name="entryId" required>{entries.map((entry) => <option value={entry.id} key={entry.id}>{entry.registryRef} — {entry.eventType}</option>)}</select></div><div className="field"><label htmlFor="field">Korygowane pole</label><input className="input" id="field" name="field" required /></div><div className="field"><label htmlFor="value">Poprawna wartość</label><input className="input" id="value" name="value" required /></div><div className="field"><label htmlFor="pin">PIN</label><input className="input pin-input" id="pin" name="pin" type="password" inputMode="numeric" maxLength={4} required /></div><div className="field full"><label htmlFor="correctionReason">Powód korekty</label><textarea className="textarea" id="correctionReason" name="reason" required minLength={5} /></div></div><button className="button primary" style={{ width: "fit-content" }}>Skoryguj wpis</button></form></div>;
}
