"use client";

import { useMemo, useState } from "react";
import { Boxes, Filter, Search, Warehouse, X } from "lucide-react";
import { WeaponGridCard, type WeaponVisual } from "@/components/weapon-ui";
import { useWeaponGridSearch } from "@/components/use-weapon-grid-search";

type WeaponItem = WeaponVisual & { brand: string; serialNumber: string; book: { series: string; name: string } };
type StockTotals = { ledger: number; reserved: number; available: number };
type CaliberStock = StockTotals & { id: string; name: string; books: (StockTotals & { id: string; series: string; name: string })[] };
type BookStock = StockTotals & { id: string; series: string; name: string; calibers: (StockTotals & { id: string; name: string })[] };

export function WeaponInventory({ weapons, groupByType }: { weapons: WeaponItem[]; groupByType: boolean }) {
  const [status, setStatus] = useState(""); const [type, setType] = useState("");
  const search = useWeaponGridSearch(weapons, (weapon) => [weapon.registryRef, weapon.name, weapon.displayName, weapon.brand, weapon.weaponSeries, weapon.serialNumber, weapon.caliber.canonicalName, weapon.book.series]);
  const filtered = useMemo(() => search.filtered.filter((weapon) => (!status || weapon.status === status) && (!type || (type === "OTHER" ? weapon.type === null : weapon.type === type))), [search.filtered, status, type]);
  const counts = { total: weapons.length, stored: weapons.filter((weapon) => weapon.status === "IN_STORAGE").length, issued: weapons.filter((weapon) => weapon.status === "ISSUED").length, inactive: weapons.filter((weapon) => !["IN_STORAGE", "ISSUED"].includes(weapon.status)).length };
  const grid = (items: WeaponItem[]) => <div className="weapon-browser-grid">{items.map((weapon) => <WeaponGridCard key={weapon.id} weapon={weapon} mode="browse" />)}</div>;
  const section = (label: string, items: WeaponItem[]) => <div className="inventory-section" key={label}><div className="inventory-section-heading"><h2>{label}</h2><span>{items.length} szt.</span></div>{grid(items)}</div>;
  return <><div className="overview-kpis"><div><span>Broń ogółem</span><strong>{counts.total}</strong></div><div><span>W magazynie</span><strong>{counts.stored}</strong></div><div><span>Wydana</span><strong>{counts.issued}</strong></div><div><span>Poza stanem</span><strong>{counts.inactive}</strong></div></div><div className="filter-bar inventory-filters"><label className="filter-search"><Search aria-hidden /><input aria-label="Szukaj broni w bazie" value={search.query} onChange={(event) => search.setQuery(event.target.value)} onKeyDown={search.onKeyDown} placeholder="Pozycja, nazwa, marka, kaliber lub numer…" /></label><label><Filter aria-hidden /><select aria-label="Status broni" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Wszystkie statusy</option><option value="IN_STORAGE">W magazynie</option><option value="ISSUED">Wydana</option><option value="WITHDRAWN">Wycofana</option><option value="TRANSFERRED">Przekazana</option><option value="DEREGISTERED">Zdjęta z ewidencji</option></select></label><select aria-label="Typ broni" value={type} onChange={(event) => setType(event.target.value)}><option value="">Wszystkie rodzaje</option><option value="HANDGUN">Broń krótka</option><option value="LONG_GUN">Broń długa</option><option value="OTHER">Inne</option></select></div>{search.exactPosition !== null && <div className="exact-position-filter">Pozycja ewidencji: <strong>{search.exactPosition}</strong><button type="button" onClick={search.clearExact} aria-label="Wyłącz dokładny filtr pozycji"><X aria-hidden /></button></div>}{groupByType ? <>{section("Broń krótka", filtered.filter((weapon) => weapon.type === "HANDGUN"))}{section("Broń długa", filtered.filter((weapon) => weapon.type === "LONG_GUN"))}{section("Inne", filtered.filter((weapon) => weapon.type === null))}</> : <div className="inventory-section">{grid(filtered)}</div>}{!filtered.length && <div className="empty-inline">Brak broni spełniającej wybrane kryteria.</div>}</>;
}

export function AmmunitionOverview({ byCaliber, byBook }: { byCaliber: CaliberStock[]; byBook: BookStock[] }) {
  const [tab, setTab] = useState<"caliber" | "book">("caliber"); const [query, setQuery] = useState(""); const needle = query.toLocaleLowerCase("pl-PL");
  const calibers = byCaliber.filter((item) => !needle || [item.name, ...item.books.flatMap((book) => [book.series, book.name])].join(" ").toLocaleLowerCase("pl-PL").includes(needle)); const books = byBook.filter((item) => !needle || [item.series, item.name, ...item.calibers.map((caliber) => caliber.name)].join(" ").toLocaleLowerCase("pl-PL").includes(needle));
  const values = (stock: StockTotals) => <span className="stock-values"><span>Ewidencyjny <strong>{stock.ledger.toLocaleString("pl-PL")}</strong></span><span>Zablokowany <strong>{stock.reserved.toLocaleString("pl-PL")}</strong></span><span>Dostępny <strong>{stock.available.toLocaleString("pl-PL")}</strong></span></span>;
  return <><div className="overview-toolbar"><div className="tabs" role="tablist"><button role="tab" aria-selected={tab === "caliber"} className={tab === "caliber" ? "active" : ""} onClick={() => setTab("caliber")}><Boxes aria-hidden />Wg kalibrów</button><button role="tab" aria-selected={tab === "book"} className={tab === "book" ? "active" : ""} onClick={() => setTab("book")}><Warehouse aria-hidden />Wg ksiąg</button></div><label className="filter-search"><Search aria-hidden /><input aria-label="Szukaj w stanie amunicji" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Kaliber lub księga…" /></label></div>{tab === "caliber" ? <div className="stock-grid">{calibers.map((caliber) => <article className="stock-card" key={caliber.id}><header><div><span>Kaliber</span><h2>{caliber.name}</h2></div><strong>{caliber.available.toLocaleString("pl-PL")} <small>dostępnych</small></strong></header>{values(caliber)}<div className="stock-components">{caliber.books.map((book) => <div key={book.id}><span><b>{book.series}</b> — {book.name}</span>{values(book)}</div>)}</div></article>)}</div> : <div className="stock-grid">{books.map((book) => <article className="stock-card book-oriented" key={book.id}><header><div><span>Księga {book.series}</span><h2>{book.name}</h2></div><strong>{book.available.toLocaleString("pl-PL")} <small>dostępnych</small></strong></header>{values(book)}<div className="stock-components">{book.calibers.map((caliber) => <div key={caliber.id}><span>{caliber.name}</span>{values(caliber)}</div>)}</div></article>)}</div>}{!(tab === "caliber" ? calibers : books).length && <div className="empty-inline">Brak stanów spełniających kryteria.</div>}</>;
}
