"use client";

import { useEffect, useId, useMemo, useRef, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { BookOpen, Check, ChevronDown, FilePlus2, Search, X } from "lucide-react";
import { DocumentForm, type DocumentOption } from "@/components/document-form";
import { Modal } from "@/components/ui-system";
import { caliberSuggestions, normalizeCaliberSearch, searchCalibers } from "@/lib/caliber-search";
import { documentTypeLabels as sharedDocumentTypeLabels } from "@/lib/labels";

export type CaliberOption = { id: string; canonicalName: string; aliases: { alias: string }[]; usageCount?: number; available?: number };
export type BookOption = { id: string; series: string; name: string; type?: string };

export function CaliberPicker({ calibers, name = "caliberId", label = "Kaliber", value, onChange }: { calibers: CaliberOption[]; name?: string; label?: string; value?: string; onChange?: (id: string) => void }) {
  const id = useId(); const [selectedId, setSelectedId] = useState(value ?? ""); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [active, setActive] = useState(0); const [recent, setRecent] = useState<string[]>(() => { if (typeof window === "undefined") return []; const saved = sessionStorage.getItem("pmb:recent-calibers"); if (!saved) return []; try { return JSON.parse(saved); } catch { return []; } }); const inputRef = useRef<HTMLInputElement>(null);
  const selected = calibers.find((item) => item.id === selectedId);
  const quick = useMemo(() => caliberSuggestions(calibers, recent), [calibers, recent]);
  const results = useMemo(() => searchCalibers(calibers, query).slice(0, 30), [calibers, query]);
  function choose(caliber: CaliberOption) { setSelectedId(caliber.id); onChange?.(caliber.id); setQuery(""); setOpen(false); const next = [caliber.id, ...recent.filter((item) => item !== caliber.id)].slice(0, 5); setRecent(next); sessionStorage.setItem("pmb:recent-calibers", JSON.stringify(next)); }
  function keyDown(event: React.KeyboardEvent<HTMLInputElement>) { if (event.key === "ArrowDown") { event.preventDefault(); setOpen(true); setActive((index) => Math.min(index + 1, results.length - 1)); } else if (event.key === "ArrowUp") { event.preventDefault(); setActive((index) => Math.max(index - 1, 0)); } else if (event.key === "Enter" && open && results[active]) { event.preventDefault(); choose(results[active]); } else if (event.key === "Escape") { setOpen(false); setQuery(""); } }
  return <div className="field caliber-picker"><label htmlFor={`${id}-search`}>{label}</label><input type="hidden" name={name} value={selectedId} required />{selected ? <div className="selected-chip"><span><Check aria-hidden />{selected.canonicalName}{selected.available !== undefined ? ` — ${selected.available.toLocaleString("pl-PL")} szt.` : ""}</span><button type="button" aria-label="Zmień kaliber" onClick={() => { setSelectedId(""); onChange?.(""); setOpen(true); setTimeout(() => inputRef.current?.focus(), 0); }}><X /></button></div> : <><div className="picker-input"><Search aria-hidden /><input ref={inputRef} id={`${id}-search`} value={query} placeholder="Wpisz nazwę lub alias…" autoComplete="off" aria-autocomplete="list" onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); setActive(0); setOpen(true); }} onKeyDown={keyDown} /><ChevronDown aria-hidden /></div>{open && <div className="picker-popover" role="listbox">{!query && <><span className="picker-caption">Ostatnio używane / popularne</span>{quick.map((caliber) => <button type="button" role="option" aria-selected="false" key={caliber.id} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(caliber)}>{caliber.canonicalName}<small>{caliber.available !== undefined ? `Stan łączny: ${caliber.available.toLocaleString("pl-PL")} szt.` : caliber.aliases.slice(0, 3).map((alias) => alias.alias).join(" · ")}</small></button>)}</>}{query && (results.length ? results.map((caliber, index) => <button type="button" role="option" className={active === index ? "active" : ""} aria-selected={active === index} key={caliber.id} onMouseDown={(event) => event.preventDefault()} onClick={() => choose(caliber)}>{caliber.canonicalName}<small>{caliber.available !== undefined ? `Stan łączny: ${caliber.available.toLocaleString("pl-PL")} szt.` : caliber.aliases.filter((alias) => normalizeCaliberSearch(alias.alias).includes(normalizeCaliberSearch(query))).slice(0, 3).map((alias) => alias.alias).join(" · ") || caliber.aliases.slice(0, 2).map((alias) => alias.alias).join(" · ")}</small></button>) : <p className="picker-empty">Brak pasującego kalibru.</p>)}</div>}</>}</div>;
}

const documentTypeLabels: Record<string, string> = sharedDocumentTypeLabels;

export function DocumentPicker({ documents: initialDocuments, name = "documentId", label = "Dokument", value, onChange }: { documents: DocumentOption[]; name?: string; label?: string; value?: string; onChange?: (id: string) => void }) {
  const [addedDocuments, setAddedDocuments] = useState<DocumentOption[]>([]); const documents = [...addedDocuments, ...initialDocuments.filter((item) => !addedDocuments.some((added) => added.id === item.id))]; const [selectedId, setSelectedId] = useState(value ?? ""); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [createOpen, setCreateOpen] = useState(false); const id = useId();
  const selected = documents.find((item) => item.id === selectedId); const needle = query.toLocaleLowerCase("pl-PL");
  const results = documents.filter((document) => !needle || [document.number, document.description, document.parties, documentTypeLabels[document.type], new Date(document.documentDate).toLocaleDateString("pl-PL")].filter(Boolean).join(" ").toLocaleLowerCase("pl-PL").includes(needle)).slice(0, 30);
  function choose(document: DocumentOption) { setSelectedId(document.id); onChange?.(document.id); setQuery(""); setOpen(false); }
  return <div className="field document-picker"><label htmlFor={`${id}-search`}>{label}</label><input type="hidden" name={name} value={selectedId} required />{selected ? <div className="selected-document"><div><FilePlus2 aria-hidden /><span><strong>{documentTypeLabels[selected.type]} {selected.number || "bez numeru"}</strong><small>{selected.description} · {new Date(selected.documentDate).toLocaleDateString("pl-PL")}</small></span></div><button type="button" className="close-button" aria-label="Zmień dokument" onClick={() => { setSelectedId(""); onChange?.(""); setOpen(true); }}><X /></button></div> : <div className="picker-input"><Search aria-hidden /><input id={`${id}-search`} value={query} placeholder="Numer, nazwa, typ, data lub podmiot…" autoComplete="off" onFocus={() => setOpen(true)} onChange={(event) => { setQuery(event.target.value); setOpen(true); }} /><ChevronDown aria-hidden /></div>}{open && !selected && <div className="picker-popover document-results" role="listbox"><button type="button" className="picker-create" onClick={() => { setCreateOpen(true); setOpen(false); }}><FilePlus2 aria-hidden />Dodaj nowy dokument</button>{results.map((document) => <button type="button" role="option" aria-selected="false" key={document.id} onClick={() => choose(document)}><strong>{documentTypeLabels[document.type]} {document.number || "bez numeru"}</strong><small>{document.description} · {new Date(document.documentDate).toLocaleDateString("pl-PL")}</small></button>)}{!results.length && <p className="picker-empty">Nie znaleziono dokumentu. Możesz utworzyć go bez opuszczania formularza.</p>}</div>}<Modal open={createOpen} title="Nowy dokument" description="Po zapisaniu dokument zostanie od razu wybrany w formularzu." onClose={() => setCreateOpen(false)} size="medium"><DocumentForm compact onCreated={(document) => { setAddedDocuments((items) => [document, ...items]); choose(document); setCreateOpen(false); }} /></Modal></div>;
}

export function BookPicker({ books, name = "bookId", label = "Księga", selectedId, onChange }: { books: BookOption[]; name?: string; label?: string; selectedId?: string; onChange?: (id: string) => void }) {
  return <div className="field book-picker"><label htmlFor={`${name}-picker`}>{label}</label><div className="book-picker-control"><BookOpen aria-hidden /><select className="select" id={`${name}-picker`} name={name} value={selectedId} defaultValue={selectedId === undefined ? "" : undefined} required onChange={(event) => onChange?.(event.target.value)}><option value="">Wybierz księgę…</option>{books.map((book) => <option key={book.id} value={book.id}>{book.series} — {book.name}</option>)}</select></div></div>;
}

export function RegisterBookPicker({ books, selectedId, storageKey }: { books: BookOption[]; selectedId: string; storageKey: string }) {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams();
  useEffect(() => { const stored = sessionStorage.getItem(storageKey); if (stored && stored !== selectedId && books.some((book) => book.id === stored) && !params.get("book")) { const next = new URLSearchParams(params.toString()); next.set("book", stored); router.replace(`${pathname}?${next}`); } }, [books, params, pathname, router, selectedId, storageKey]);
  return <BookPicker books={books} label="Wybierz księgę" selectedId={selectedId} onChange={(id) => { sessionStorage.setItem(storageKey, id); const next = new URLSearchParams(params.toString()); next.set("book", id); router.replace(`${pathname}?${next}`); }} />;
}
