import { z } from "zod";

export const loginSchema = z.object({ login: z.string().trim().min(1).max(80), password: z.string().min(1).max(200) });
export const passwordSchema = z.string().min(12, "Hasło musi mieć co najmniej 12 znaków.").max(200).regex(/[A-ZĄĆĘŁŃÓŚŹŻ]/, "Dodaj wielką literę.").regex(/[a-ząćęłńóśźż]/, "Dodaj małą literę.").regex(/\d/, "Dodaj cyfrę.");
export const pinSchema = z.string().regex(/^\d{4}$/, "PIN musi mieć dokładnie 4 cyfry.");
export const onboardingSchema = z.object({ firstName: z.string().trim().min(2).max(80), lastName: z.string().trim().min(2).max(100), login: z.string().trim().min(3).max(80).regex(/^[a-zA-Z0-9._-]+$/), temporaryPassword: passwordSchema });
export const changePasswordSchema = z.object({ password: passwordSchema, confirmation: z.string() }).refine((data) => data.password === data.confirmation, { message: "Hasła nie są takie same.", path: ["confirmation"] });
export const documentSchema = z.object({ type: z.enum(["INVOICE", "AGREEMENT", "TRANSFER_DOCUMENT", "WITHDRAWAL_DOCUMENT", "AUTHORIZATION", "OTHER"]), number: z.string().trim().max(100).optional(), documentDate: z.coerce.date(), description: z.string().trim().min(3).max(500), parties: z.string().trim().max(500).optional() });
export const bookSchema = z.object({ type: z.enum(["WEAPON", "AMMUNITION", "WEAPON_ISSUE", "AMMUNITION_ISSUE"]), series: z.string().trim().toUpperCase().regex(/^[A-Z]{1,2}$/), name: z.string().trim().min(2).max(120) });
export const weaponInputSchema = z.object({ bookId: z.string().min(1), caliberId: z.string().min(1), documentId: z.string().min(1), name: z.string().trim().min(2).max(120), brand: z.string().trim().min(1).max(100), productionYear: z.coerce.number().int().min(1800).max(new Date().getFullYear() + 1).optional(), weaponSeries: z.string().trim().max(100).optional(), serialNumber: z.string().trim().min(1).max(120), otherIdentifyingMarks: z.string().trim().max(500).optional(), accessories: z.string().trim().max(500).optional(), type: z.enum(["HANDGUN", "LONG_GUN"]), acquisitionBasis: z.string().trim().min(3).max(500), acquisitionDate: z.coerce.date().optional(), registeredAt: z.coerce.date(), certificateNumber: z.string().trim().max(120).optional(), notes: z.string().trim().max(1000).optional(), pin: pinSchema });
export const ammoAcquisitionSchema = z.object({ bookId: z.string().min(1), caliberId: z.string().min(1), documentId: z.string().min(1), ammunitionType: z.string().trim().min(2).max(120), quantity: z.coerce.number().int().positive().max(10_000_000), basis: z.string().trim().min(3).max(500), effectiveAt: z.coerce.date(), pin: pinSchema });
export const issueWeaponSchema = z.object({ weaponId: z.string().min(1), bookId: z.string().min(1), recipientName: z.string().trim().min(2).max(160), recipientReference: z.string().trim().max(120).optional(), magazineCount: z.coerce.number().int().min(0).max(100), pin: pinSchema, ammo: z.object({ issueBookId: z.string().min(1), sourceBookId: z.string().min(1), quantity: z.coerce.number().int().positive(), ammunitionType: z.string().trim().min(2).max(120) }).optional() });
export const returnWeaponSchema = z.object({ issueId: z.string().min(1), returnedFromName: z.string().trim().min(2).max(160), returnedAmmoQuantity: z.coerce.number().int().min(0).optional(), pin: pinSchema });
export const issueAmmoSchema = z.object({ bookId: z.string().min(1), sourceBookId: z.string().min(1), caliberId: z.string().min(1), ammunitionType: z.string().trim().min(2).max(120), quantity: z.coerce.number().int().positive(), recipientName: z.string().trim().min(2).max(160), recipientReference: z.string().trim().max(120).optional(), pin: pinSchema, parentIssueId: z.string().optional() });
export const returnAmmoSchema = z.object({ issueId: z.string().min(1), returnedQuantity: z.coerce.number().int().min(0), pin: pinSchema });
