import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { PageHeader } from "@/components/page-header";
import { formatDateTime } from "@/lib/utils";
import { WeaponHistoryControls } from "@/components/history-controls";

export const metadata = { title: "Karta broni" };
export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const weapon = await prisma.weapon.findUnique({ where: { id }, include: { caliber: true, book: true, acquisitionDocument: true, events: { include: { document: true }, orderBy: { effectiveAt: "desc" } }, registerEntries: { include: { corrections: true }, orderBy: { effectiveAt: "desc" } }, verificationFlags: { orderBy: { createdAt: "desc" } } } }); if (!weapon) notFound();
  return <div className="page"><PageHeader eyebrow="Karta broni" title={`${weapon.registryRef} — ${weapon.name}`} description={`${weapon.brand} • ${weapon.caliber.canonicalName} • numer ${weapon.serialNumber}`} /><section className="page-card"><h2 className="section-heading">Dane bieżące</h2><dl className="detail-list"><div className="detail-row"><dt>Księga i Lp</dt><dd>{weapon.book.series} / {weapon.positionNo}</dd></div><div className="detail-row"><dt>Status</dt><dd>{weapon.status}</dd></div><div className="detail-row"><dt>Rok produkcji</dt><dd>{weapon.productionYear ?? "—"}</dd></div><div className="detail-row"><dt>Seria i numer</dt><dd>{weapon.weaponSeries ?? "—"} / {weapon.serialNumber}</dd></div><div className="detail-row"><dt>Wyposażenie</dt><dd>{weapon.accessories ?? "—"}</dd></div><div className="detail-row"><dt>Podstawa nabycia</dt><dd>{weapon.acquisitionBasis}</dd></div><div className="detail-row"><dt>Dokument</dt><dd>{weapon.acquisitionDocument.number ?? weapon.acquisitionDocument.description}</dd></div></dl></section><section className="page-card"><h2 className="section-heading">Historia chronologiczna</h2><div className="paper-table-wrap"><table className="paper-table"><thead><tr><th>Data</th><th>Zdarzenie</th><th>Osoba</th><th>Podstawa / dokument</th><th>Potwierdzenie</th></tr></thead><tbody>{weapon.events.map((event) => <tr key={event.id}><td>{formatDateTime(event.effectiveAt)}</td><td>{event.type}</td><td>{event.performedByName}</td><td>{event.basis ?? event.document?.description ?? "—"}</td><td>{event.confirmationMethod ? `${event.confirmationMethod}, ${formatDateTime(event.confirmedAt)}` : "System"}</td></tr>)}</tbody></table></div></section><section className="page-card no-print"><WeaponHistoryControls weaponId={weapon.id} entries={weapon.registerEntries} openFlags={weapon.verificationFlags.filter((flag) => !flag.resolvedAt)} /></section></div>;
}
