import { prisma } from "@/lib/db";
import { PageHeader } from "@/components/page-header";
import { PrintButton } from "@/components/admin-controls";
import { formatDateTime } from "@/lib/utils";
import Link from "next/link";

export const metadata = { title: "Książka wydawania broni" };
export default async function Page() {
  const books = await prisma.registerBook.findMany({ where: { type: "WEAPON_ISSUE" }, include: { weaponIssues: { include: { weapon: true }, orderBy: { positionNo: "asc" } } }, orderBy: { series: "asc" } });
  return <div className="page"><PageHeader eyebrow="Rejestry zgodne z prawem" title="Ewidencja wydawania i przyjmowania broni" description="Dane broni są snapshotem z chwili wydania i nie zmienią się po późniejszej korekcie karty." actions={<PrintButton />} />{books.map((book) => <section className="page-card" key={book.id}><div className="paper-table-wrap"><table className="legal-register"><caption>Księga {book.series} — {book.name}</caption><thead><tr><th>Lp</th><th>Data i godzina wydania broni</th><th>Nazwa i marka broni</th><th>Kaliber broni i rok produkcji</th><th>Seria i numer broni</th><th>Ilość magazynków</th><th>Numer świadectwa broni</th><th>Imię i nazwisko wydającego</th><th>Imię i nazwisko przyjmującego</th><th>Data i godzina przyjęcia broni</th><th>Imię i nazwisko zdającego</th><th className="no-print">Status</th></tr></thead><tbody>{book.weaponIssues.map((issue) => <tr key={issue.id}><td><Link className="registry-link" href={`/weapons/${issue.weapon.id}`}>{issue.positionNo}</Link></td><td>{formatDateTime(issue.issuedAt)}</td><td><Link className="record-link" href={`/weapons/${issue.weapon.id}`}>{issue.weaponNameSnapshot} / {issue.weaponBrandSnapshot}<small>{issue.weapon.registryRef}</small></Link></td><td>{issue.caliberSnapshot}{issue.productionYearSnapshot ? ` / ${issue.productionYearSnapshot}` : ""}</td><td>{issue.weaponSeriesSnapshot ? `${issue.weaponSeriesSnapshot} / ` : ""}{issue.serialNumberSnapshot}</td><td>{issue.magazineCount}</td><td>{issue.certificateSnapshot ?? "—"}</td><td>{issue.issuedByName}</td><td>{issue.recipientName}</td><td>{formatDateTime(issue.returnedAt)}</td><td>{issue.returnedFromName ?? "—"}</td><td className="no-print"><span className={`badge ${issue.status === "ACTIVE" ? "warn" : "ok"}`}>{issue.status === "ACTIVE" ? "Wydana" : "Przyjęta"}</span></td></tr>)}</tbody></table></div></section>)}</div>;
}
