import Link from "next/link";
import { prisma } from "@/lib/db";
import { PageHeader } from "@/components/page-header";
import { PrintButton } from "@/components/admin-controls";
import { formatDateTime } from "@/lib/utils";

export const metadata = { title: "Raport kontroli" };
export default async function Page() {
  const [total, storage, issued, inactive, users, operations, activeWeaponIssues, activeAmmoIssues, flags, ammoTotals] = await Promise.all([prisma.weapon.count(), prisma.weapon.count({ where: { status: "IN_STORAGE" } }), prisma.weapon.count({ where: { status: "ISSUED" } }), prisma.weapon.count({ where: { status: { in: ["WITHDRAWN", "TRANSFERRED", "DEREGISTERED"] } } }), prisma.user.count({ where: { active: true, isBootstrap: false } }), prisma.auditEvent.findMany({ orderBy: { sequence: "desc" }, take: 10 }), prisma.weaponIssue.count({ where: { status: "ACTIVE" } }), prisma.ammoIssue.count({ where: { status: "ACTIVE" } }), prisma.physicalVerificationFlag.findMany({ where: { resolvedAt: null }, include: { weapon: true }, orderBy: { createdAt: "desc" } }), prisma.ammunitionRegisterEntry.aggregate({ _sum: { quantityIn: true, quantityOut: true } })]);
  const ammo = (ammoTotals._sum.quantityIn ?? 0) - (ammoTotals._sum.quantityOut ?? 0);
  return <div className="page"><PageHeader eyebrow="Dokumenty / raporty" title="Raport kontroli magazynu" description={`Wygenerowano ${formatDateTime(new Date())}`} actions={<PrintButton />} /><div className="kpis"><div className="kpi"><div><span>Broń ogółem</span><strong>{total}</strong></div></div><div className="kpi"><div><span>W magazynie</span><strong>{storage}</strong></div></div><div className="kpi"><div><span>Wydana</span><strong>{issued}</strong></div></div><div className="kpi"><div><span>Wycofana / przekazana</span><strong>{inactive}</strong></div></div><div className="kpi"><div><span>Stan amunicji</span><strong>{ammo.toLocaleString("pl-PL")}</strong></div></div></div><div className="dashboard-grid"><section className="page-card"><h2 className="section-heading">Stan operacyjny</h2><dl className="detail-list"><div className="detail-row"><dt>Aktywni użytkownicy</dt><dd>{users}</dd></div><div className="detail-row"><dt>Aktywne wydania broni</dt><dd>{activeWeaponIssues}</dd></div><div className="detail-row"><dt>Aktywne wydania amunicji</dt><dd>{activeAmmoIssues}</dd></div><div className="detail-row"><dt>Pozycje do sprawdzenia fizycznego</dt><dd className={flags.length ? "red" : "green"}>{flags.length}</dd></div></dl></section><section className="page-card"><h2 className="section-heading">Wymagają fizycznego sprawdzenia</h2>{flags.length ? flags.map((flag) => <p key={flag.id}><strong>{flag.weapon?.registryRef ?? flag.entityId}</strong> — {flag.reason} <span className="muted">({formatDateTime(flag.createdAt)})</span></p>) : <div className="success-box">Brak nierozwiązanych flag kontroli.</div>}</section></div><section className="page-card"><h2 className="section-heading">Ostatnie operacje</h2><div className="paper-table-wrap"><table className="paper-table"><thead><tr><th>Data</th><th>Operacja</th><th>Typ</th><th>Użytkownik</th></tr></thead><tbody>{operations.map((event) => <tr key={event.id}><td>{formatDateTime(event.timestamp)}</td><td>{event.operation}</td><td>{event.entityType}</td><td>{event.userSnapshot ?? "System"}</td></tr>)}</tbody></table></div></section><p className="small muted">Raport wspiera kontrolę ewidencji; nie zastępuje fizycznego sprawdzenia magazynu. <Link href="/administration/audit">Sprawdź integralność audytu</Link>.</p></div>;
}
